### ISSUE TITLE
Availability of trained weights

### ISSUE THREAD

**Issue by TortillasAlfred** [pg2455/Hybrid-learn2branch#3]
Hi,

I really liked your paper and thank you for publicly releasing your codebase. 

I wondered if there is any way to have access to the final trained weights used to produce the tables in the paper else than redoing the training from scratch ? This would help me very much help in accurately comparing my technique to this one. 

If ever the trained weights are available somewhere that I missed, please excuse me for missing it and just point me towards where to get them.

Thank you and have a good day.

**Comment by pg2455** [comment]
Hello! Sorry for such a massive delay in responding. I entirely missed these issues on the repo. Unfortunately, the trained weights have been removed from the backup. This is a good lesson. I will keep that in mind while releasing any future work. Thanks for bringing that to my attention.
